# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcs_system_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('directed_graph', models.FileField(blank=True, null=True, upload_to='computed_files/')),
                ('directed_pickle', models.FileField(blank=True, null=True, upload_to='computed_files/')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
