# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0002_commitlabelfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcs_system_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='computed_files/')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
