# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('stats_date', models.DateField(auto_now=True)),
                ('number_commits', models.IntegerField(default=0)),
                ('number_issues', models.IntegerField(default=0)),
                ('number_files', models.IntegerField(default=0)),
                ('number_messages', models.IntegerField(default=0)),
                ('number_people', models.IntegerField(default=0)),
            ],
        ),
    ]
