# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0004_projectstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
