# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 15:04
from __future__ import unicode_literals

from django.db import migrations


def add_job_types(apps, schema_editor):
    hjt = apps.get_model("visualSHARK", "VSJobType")

    for t in ['collect_repo', 'test_connection_servershark', 'test_connection_worker', 'fetch_commit_labels', 'create_commit_graph']:
        h = hjt()
        h.name = t
        h.ident = t
        h.save()


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0006_auto_20171125_0922'),
    ]

    operations = [
        migrations.RunPython(add_job_types),
    ]
