# Generated by Django 2.2.4 on 2019-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0008_issuevalidation_issuevalidationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_commits', 'View commits'), ('view_issues', 'View issues'), ('view_people', 'View people'), ('view_files', 'View files'), ('view_messages', 'View messages'), ('view_analytics', 'View Analytics'), ('view_issue_links', 'View issue links rights'), ('edit_issue_links', 'Edit issue links rights'), ('view_issue_labels', 'View issue labels rights'), ('edit_issue_labels', 'Edit issue labels rights'), ('view_issue_conflicts', 'View issue label conflict right'), ('edit_issue_conflicts', 'View issue label conflict right')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
