# Generated by Django 2.2.10 on 2020-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0009_projectattributes_rightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('view_stats', 'View stats'), ('view_commits', 'View commits'), ('view_issues', 'View issues'), ('view_people', 'View people'), ('view_files', 'View files'), ('view_projects', 'View projects'), ('view_messages', 'View messages'), ('view_analytics', 'View analytics'), ('view_issue_links', 'View issue links'), ('edit_issue_links', 'Edit issue links'), ('view_issue_labels', 'View issue labels'), ('edit_issue_labels', 'Edit issue labels'), ('view_issue_conflicts', 'View issue label conflicts'), ('edit_issue_conflicts', 'Edit issue label conflicts'), ('view_jobs', 'View jobs'), ('edit_jobs', 'Edit jobs'), ('view_line_labels', 'View line labels'), ('edit_line_labels', 'Edit line labels'))},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line_label_has_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line_label_last_issue_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
