# Generated by Django 2.2.10 on 2020-11-18 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualSHARK', '0011_leaderboardsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('view_stats', 'View stats'), ('view_commits', 'View commits'), ('view_issues', 'View issues'), ('view_people', 'View people'), ('view_files', 'View files'), ('view_projects', 'View projects'), ('view_messages', 'View messages'), ('view_analytics', 'View analytics'), ('view_issue_links', 'View issue links'), ('edit_issue_links', 'Edit issue links'), ('view_issue_labels', 'View issue labels'), ('edit_issue_labels', 'Edit issue labels'), ('view_issue_conflicts', 'View issue label conflicts'), ('edit_issue_conflicts', 'Edit issue label conflicts'), ('view_jobs', 'View jobs'), ('edit_jobs', 'Edit jobs'), ('view_line_labels', 'View line labels'), ('edit_line_labels', 'Edit line labels'), ('view_technology_labels', 'View technology labels'), ('edit_technology_labels', 'Edit technology labels'), ('view_line_label_corrections', 'View line label corrections'), ('edit_line_label_corrections', 'Set line label corrections'))},
        ),
        migrations.CreateModel(
            name='CorrectionIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('is_corrected', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
