# Generated by Django 2.2.10 on 2020-11-23 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualSHARK', '0012_auto_20201118_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('is_corrected', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('changes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CorrectionIssues',
        ),
    ]
