# Generated by Django 2.2.10 on 2020-11-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0013_auto_20201123_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionissue',
            name='project_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
