# Generated by Django 2.2.10 on 2020-11-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0014_correctionissue_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionissue',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
