# Generated by Django 2.2.10 on 2020-12-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualSHARK', '0015_correctionissue_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMDIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
