# Generated by Django 2.2.13 on 2020-12-21 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualSHARK', '0015_correctionissue_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('times_used', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('view_stats', 'View stats'), ('view_commits', 'View commits'), ('view_issues', 'View issues'), ('view_people', 'View people'), ('view_files', 'View files'), ('view_projects', 'View projects'), ('view_messages', 'View messages'), ('view_analytics', 'View analytics'), ('view_issue_links', 'View issue links'), ('edit_issue_links', 'Edit issue links'), ('view_issue_labels', 'View issue labels'), ('edit_issue_labels', 'Edit issue labels'), ('view_issue_conflicts', 'View issue label conflicts'), ('edit_issue_conflicts', 'Edit issue label conflicts'), ('view_jobs', 'View jobs'), ('edit_jobs', 'Edit jobs'), ('view_line_labels', 'View line labels'), ('edit_line_labels', 'Edit line labels'), ('view_technology_labels', 'View technology labels'), ('edit_technology_labels', 'Edit technology labels'), ('view_line_label_corrections', 'View line label corrections'), ('edit_line_label_corrections', 'Set line label corrections'), ('view_change_labels', 'View change labels'), ('edit_change_labels', 'Set change labels'))},
        ),
        migrations.CreateModel(
            name='TechnologyLabelCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_hash', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('is_labeled', models.BooleanField(default=False)),
                ('changes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeTypeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_hash', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('has_label', models.BooleanField(default=False)),
                ('is_perfective', models.BooleanField(default=False)),
                ('is_corrective', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
