# Generated by Django 2.2.13 on 2020-12-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0016_auto_20201221_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologylabelcommit',
            name='has_technology',
            field=models.BooleanField(default=False),
        ),
    ]
