# Generated by Django 2.2.13 on 2020-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0019_auto_20201227_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('view_stats', 'View stats'), ('view_commits', 'View commits'), ('view_issues', 'View issues'), ('view_people', 'View people'), ('view_files', 'View files'), ('view_projects', 'View projects'), ('view_messages', 'View messages'), ('view_analytics', 'View analytics'), ('view_issue_links', 'View issue links'), ('edit_issue_links', 'Edit issue links'), ('view_issue_labels', 'View issue labels'), ('edit_issue_labels', 'Edit issue labels'), ('view_issue_conflicts', 'View issue label conflicts'), ('edit_issue_conflicts', 'Edit issue label conflicts'), ('view_jobs', 'View jobs'), ('edit_jobs', 'Edit jobs'), ('view_line_labels', 'View line labels'), ('edit_line_labels', 'Edit line labels'), ('view_technology_labels', 'View technology labels'), ('edit_technology_labels', 'Edit technology labels'), ('view_line_label_corrections', 'View line label corrections'), ('edit_line_label_corrections', 'Set line label corrections'), ('view_change_labels', 'View change labels'), ('edit_change_labels', 'Set change labels'), ('view_pull_requests', 'View pull requests'))},
        ),
        migrations.AlterField(
            model_name='technologylabelcommit',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='visualSHARK.TechnologyLabel'),
        ),
    ]
