# Generated by Django 2.2.13 on 2021-01-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0020_auto_20201230_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTypeLabelDisagreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_hash', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('has_label', models.BooleanField(default=False)),
                ('is_perfective', models.BooleanField(default=False)),
                ('is_corrective', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
