# Generated by Django 2.2.13 on 2026-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualSHARK', '0021_changetypelabeldisagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuevalidation',
            name='linked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuevalidation',
            name='resolution',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
